---
# load variables

- import_playbook: variables.yml

# install nodejs environment
- name: Install Nodejs Environment
  hosts: app
  become: true
  tasks:

    # Add the nodesource apt key to the ubuntu server
    - name: Add Nodesource apt key.
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    # Add the NodeSource Nodejs repository to the server

    - name: Add NodeSource repositories for Node.js.
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
      register: node_repo

    # Update the repository cache only when the repository has changed
    - name: Update apt cache if repo was added.
      apt: update_cache=yes
      when: node_repo.changed

    # Install Nodejs, nginx, and git to the server

    - name: Install Required packages For app Deployment
      apt: name={{item}} state=present
      with_items: "{{ app_dependencies }}"
